[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "RANDOM SECRET STRING"

[auth.auth0]
client_id = "CLIENT_ID_XXX"
client_secret = "CLIENT_SECRET_XXX"
server_metadata_url = "https://{AUTH0_DOMAIN}/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }